//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int SessionId { get; set; }
        public int StudentId { get; set; }
        public int AttendanceTypeId { get; set; }
        public Nullable<int> ReasonId { get; set; }
        public Nullable<System.DateTime> CreationDtTm { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual Reason Reason { get; set; }
        public virtual Session Session { get; set; }
        public virtual Student Student { get; set; }
    }
}
